- name: copy nginx.conf no Cache
  copy:
    src: nginxconf/noCache/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy nginx default.conf no Cache - default config
  copy:
    src: nginxconf/noCache/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: start nginx no Cache
  ansible.builtin.systemd:
    name: nginx.service
    state: started   
    enabled: true
