- name: copy nginxconf with cache
  when: inventory_hostname in groups['vmnginxwithcache']
  copy:
    src: nginxconf/withCache/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy nginx default.con with cache - default config
  when: inventory_hostname in groups['vmnginxwithcache']
  copy:
    src: nginxconf/withCache/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: start nginx with cache
  when: inventory_hostname in groups['vmnginxwithcache']
  shell: systemctl start nginx && systemctl enable nginx
