- name: copy nginxconf with cache
  copy:
    src: nginxconf/withCache/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy nginx default.con with cache - default config
  copy:
    src: nginxconf/withCache/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: start nginx with cache
  ansible.builtin.systemd:
    name: nginx.service
    state: started   
    enabled: true
