- name: webinfrastructure
  hosts: 
    - avelon
  become: yes
  remote_user: avelon
  collections:
    - community.docker

  vars: 
    varReboot: false


  pre_tasks:
    - name: install necessary apache packages
      when: inventory_hostname in groups['vmapache']
      apt:
        name: 
          - docker.io
          - git
        state: latest

    - name: install necessary mariadb packages
      when: inventory_hostname in groups['vmmariadb']
      apt:
        name: 
          - mariadb-server
          - git
        state: latest

    - name: install necessary dns packages
      when: inventory_hostname in groups['vmdns']
      apt:
        name: 
          - dnsmasq
          - git
        state: latest

    - name: stop systemd-resolved
      when: inventory_hostname in groups['vmdns']
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: stopped         
        enabled: false
        masked: no

    - name: install necessary nginx packages
      when: 
        - inventory_hostname in groups['vmnginxnocache'] or inventory_hostname in groups['vmnginxwithcache']
      apt:
        name: 
          - nginx
          - git
        state: latest

    - name: create user nginx for bug fixing
      when: inventory_hostname in groups['vmnginxnocache'] or inventory_hostname in groups['vmnginxwithcache']    
      user:
        name: nginx
        shell: /bin/false

  roles:
    - role: startdns
      when: inventory_hostname in groups['vmdns']    
    - role: startmariadb 
      when: inventory_hostname in groups['vmmariadb']
    - role: startnginxwithcache
      when: inventory_hostname in groups['vmnginxwithcache']
    - role: startnginxnocache
      when: inventory_hostname in groups['vmnginxnocache']
    - role: startwordpress
      when: inventory_hostname in groups['vmapache']



  post_tasks:
    - name: reboot all hosts
      reboot:
      when: varReboot is defined and varReboot
        
    - name: start systmed-resolved
      when: inventory_hostname in groups['vmdns']
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: started   

    - name: stop systemd-resolved
      when: inventory_hostname in groups['vmdns']
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: stopped   

    - name: start dnsmasq
      when: inventory_hostname in groups['vmdns']
      ansible.builtin.systemd:
        name: dnsmasq
        state: started           
