- name: webinfrastructure
  hosts: 
    - vmapache
    - vmmariadb
    - vmnginxnocache
    - vmnginxwithcache
    - vmdns
  become: yes
  remote_user: avelon

  vars: 
    varReboot: false


  pre_tasks:
    - name: install necessary apache packages
      when: inventory_hostname in groups['vmapache']
      apt:
        name: 
          - docker.io
          - git
        state: latest

    - name: install necessary mariadb packages
      when: inventory_hostname in groups['vmmariadb']
      apt:
        name: 
          - mariadb-server
          - git
        state: latest

    - name: install necessary dns packages
      when: inventory_hostname in groups['vmdns']
      apt:
        name: 
          - dnsmasq
          - git
        state: latest

    - name: install necessary nginx packages
      when: 
        - inventory_hostname in groups['vmnginxnocache'] or inventory_hostname in groups['vmnginxwithcache']
      apt:
        name: 
          - nginx
          - git
        state: latest

    - name: create user nginx for bug fixing
      when: inventory_hostname in groups['vmnginxnocache'] or inventory_hostname in groups['vmnginxwithcache']    
      user:
        name: nginx
        shell: /bin/false

  roles:
    - startInfrastructure


  post_tasks:
    - name: reboot all hosts
      reboot:
      when: varReboot is defined and varReboot